### ISSUE TITLE
`fspp` property returned is not formatted as List

### ISSUE THREAD

**Issue by trailmax** [PavelMatua/LinqToMoz#3]
I'm getting serialisation error when using paid subscribtion. Property `fspp` returns as "http://yandex.ru http://yandex.ru/internet/ http://yandex.ru/video http://yandex.ru/advanced.html http://yandex.ru/video/ https://yandex.ru/blog/company", so it can't be serialised into `List<String>`. 

Either it should be just as string or have a special serialiser that takes space-separated words and puts them in the list

**Comment by PavelMatua** [comment]
Hi Max, thanks for your notes. 
Yep I think it is possible to override getter and separate it into list of string. Unfortunately I doesn't have payed version. So I'll check it as simple JSON. And deploy it. If you'll be able to check after, I will be grateful. 
If there are some other error don't hesitate to report about it.
Thanks

**Comment by trailmax** [comment]
If you tell me your email, I'll be able to send you a small sample of data I can get from the paid subscription and you'll be able to test it better yourself.

**Comment by PavelMatua** [comment]
Sure, take this one: pmatuadev@gmail.com

**Comment by PavelMatua** [comment]
Done. I've solved this problem by implementing JsonConverter. and using annotation at URLMetricsContext after.
